SurveysSystem/Controllers/ElementsController.cs
using SurveysSystem.Models;
using SurveysSystem_Model.Abstract;
using SurveysSystem_Model.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SurveysSystem.Controllers
{
    [Authorize]
    public class ElementsController : Controller
    {
        //obiekt reprezentujący repozytorium danych
        private IRepositories repository;

        public ElementsController(IRepositories repo)
        {
            repository = repo;
        }

        #region dodawanie pytań

        [HttpGet]
        public ActionResult Edit()
        {
            //tworzenie nowego obiektu modelu widoku ElementsModel
            //w celu uzupełnienia początkowo wyświetlanych danych
            ElementsModel element = new ElementsModel(); 
        
            //tworzenie listy wyboru ilości odpowiedzi
            List<int> numbers = new List<int>();
            for (int i = 1; i < 6; i++)
            {
                numbers.Add(i);
            }
            SelectList numberList = new SelectList(numbers);
            ViewBag.Numbers = numberList;
            return View(element);
        }

        [HttpPost]
        public ActionResult Edit(ElementsModel element, string buttonType)
        {
            //wiadomości przekazywane do widoku
            string messageOk = "";
            string messageError1 = "W bazie istnieje już";
            string messageError2 = "Pole nie może być puste.";

            //tworzenie nowych obiektow potrzebych typow
            Question question = new Question();
            AnswerSet answerSet = new AnswerSet();

            //tworzenie listy wyboru ilości odpowiedzi
            List<int> numbers = new List<int>();
            for (int i = 1; i < 6; i++)
            {
                numbers.Add(i);
            }
            SelectList numberList = new SelectList(numbers);
            ViewBag.Numbers = numberList;

            if (buttonType == "Zapisz")
            {
                //sprawdzanie poprawnosci modelu w celu zapisu danych do bazy
                if (ModelState.IsValid)
                {
                    //jezeli metoda zapisu tresci do bazy zwróciła wartość
                    //świadczącą o powodzeniu,
                    //następudo dodanie do bazy kolejnego elementu
                    string questionSuccess = repository.SaveContent(element.Question);

                    if (questionSuccess == messageOk)
                    {
                        //dodanie pytania do bazy
                        //gdzie wartoscia jest identyfikator tresci
                        question.content_id = element.Question.id;
                        repository.SaveQuestion(question);
                    }
                    //procedura w razie błęu
                    else if (questionSuccess == messageError1)
                    {
                        TempData["questionMessage"] = string.Format(messageError1 + " takie pytanie.");
                    }
                    else if (questionSuccess == messageError2)
                    {
                        TempData["questionMessage"] = string.Format(messageError2);
                    }

                    //zapamietanie wybranej ilosci odpowiedzi
                    if (element.Amount_of_answers >= 0)
                    {
                        ViewBag.AnswersAmount = element.Amount_of_answers;
                    }
                    
                    //procedura w razie błęu
                    else
                    {
                        TempData["amountMessage"] = string.Format(messageError2);
                    }

                    
                        //dodawanie do bazy zestawów odpowiedzi
                        //są one dodawane w postaci zbioru identyfiaktórw 
                        //odpowiednich treści oddzielonych średnikiem, 
                        //np: 62;63;65
                        List<int> IDList = new List<int>();
                        string answerSuccess = messageError2;

                        for (int i = 0; i < element.Amount_of_answers; i++)
                        {
                            //zapis kolejnych tresci
                            answerSuccess = repository.SaveContent(element.Answer[i]);

                            if (answerSuccess == messageOk)
                            {
                                IDList.Add(element.Answer[i].id);
                            }
                            else if (answerSuccess == messageError1)
                            {
                                TempData["answerMessage"] = string.Format(messageError1 + " taka odpowiedź.");
                            }
                            else if (answerSuccess == messageError2)
                            {
                                TempData["answerMessage"] = string.Format(messageError2);
                            }
                        }

                        if (IDList.Count > 0)
                        {
                            //tworzenie odpowiedniej formy zestawu odpowiedzi
                            foreach (var item in IDList)
                            {
                                answerSet.content_id += item.ToString() + ';';
                            }
                            //zapis zestawu odpowiedzi do bazy
                            repository.SaveAnswers(answerSet);
                        }
                    
                    //informacja w razie sukcesu
                    TempData["message"] = string.Format("Zapisano nowy element ankiety.");
                    ModelState.Clear();
                   
                }
                else
                {
                    //informacja w razie błedu
                    TempData["message"] = string.Format("Coś nie tak.");
                    ModelState.Clear();
                }
                return View(element);
            }

            if (buttonType == "Nowe pytanie")
            {
                return View(new ElementsModel());
            }

            return View(element);
        }
        #endregion

#region ukladanie ankiety

        [HttpGet]
        public ActionResult CreateSurvey()
        {
            #region wyswietlanie danych w drop down listach
            SurveysModel surveyModel = new SurveysModel();
            surveyModel.AnswerType = new SelectList(repository.Types, "id", "type");
            
            List<Content> contents = repository.Contents.ToList();

            List<Content> surveyTitles = new List<Content>();

            foreach (var item in contents)
            {
                if (repository.Surveys.Any(e => e.content_id == item.id))
                {
                    surveyTitles.Add(item);
                }
            }

            surveyModel.SurveyTitleToChoose = new SelectList(surveyTitles, "id", "text");

            List<Content> questions = new List<Content>();

            foreach (var item in contents)
            {
                if (repository.Questions.Any(e=>e.content_id==item.id))
                {
                    questions.Add(item);
                }
            }

            surveyModel.QuestionsToChoose = new SelectList(questions, "id", "text");

            List<Content> answers = new List<SurveysSystem_Model.Entities.Content>();

            Dictionary<int, string[]> answerSplitList = new Dictionary<int, string[]>();

            string[] answerSplit;

            string answerElement = "";


            List<AnswerSet> lista = new List<AnswerSet>();
            lista = repository.AnswerSets.ToList();

            foreach (var item in repository.AnswerSets)
            {
                answerSplit = item.content_id.Split(';');
                answerSplitList.Add(item.id, answerSplit);
            }

            var enumerator = answerSplitList.GetEnumerator();

            while (enumerator.MoveNext())
            {
                var pair = enumerator.Current;
               

                for (int i = 0; i < pair.Value.Count(); i++)
                {
                    if (contents.Any(e => e.id.ToString() == pair.Value[i]))
                    {
                        answerElement += contents.First(e => e.id.ToString() == pair.Value[i]).text + ';';
                    }
                }
                Content answCont = new SurveysSystem_Model.Entities.Content(); //!!!!!!! tutaj trzeba bylo zadeklarowac zmienna
                answCont.id = pair.Key;
                answCont.text = answerElement;
                answers.Add(answCont);
                answerElement = "";

            }

            surveyModel.AnswersToChoose = new SelectList(answers, "id", "text");
            #endregion

            return View(surveyModel);
        }

        [HttpPost]
        public ActionResult CreateSurvey(SurveysModel surveyModel, string buttonType)
        {
            string messageOk = "";
            string messageError1 = "W bazie istnieje już";
            string messageError2 = "Wybierz element z listy.";

            Question question = new Question();
            AnswerSet answerSet = new AnswerSet();
            Survey survey = new Survey();
            SurveyElement surveyElement = new SurveyElement();

            #region uzupelnianie drop down list
            List<Content> contents = repository.Contents.ToList();

            List<Content> surveyTitles = new List<Content>();

            foreach (var item in contents)
            {
                if (repository.Surveys.Any(e => e.content_id == item.id))
                {
                    surveyTitles.Add(item);
                }
            }

            surveyModel.SurveyTitleToChoose = new SelectList(surveyTitles, "id", "text");

            List<Content> questions = new List<Content>();

            foreach (var item in contents)
            {
                if (repository.Questions.Any(e => e.content_id == item.id))

SurveysSystem/Views/Elements/CreateSurvey.cshtml
@model SurveysSystem.Models.SurveysModel

@{
    ViewBag.Title = "CreateSurvey";
}

<h2>Układanie ankiety</h2>
@using (Html.BeginForm("CreateSurvey", "Elements"))
{
    @Html.ValidationSummary(false)

    <div class="editor-label">
         <br />
        <div>@Html.LabelFor(e => e.SelectedTitle)
           
            @if (TempData["surveyMessage"] != null)
            {
                <div style="color: red">
                    @TempData["surveyMessage"]
                </div>
            }
            <br />
        </div>
    </div>
    
    <div class="editor-field">

        <div>@Html.DropDownListFor(e => e.SelectedTitle, Model.SurveyTitleToChoose)</div>
        @Html.ValidationMessageFor(m => m.SelectedTitle)

    </div>

    <div class="editor-label">
        <br />
           <div>@Html.LabelFor(e=>e.SurveyTitleTextBox)
               
               @if (TempData["surveyMessage"] != null)
	            {
                   <div style="color:red">
		            @TempData["surveyMessage"]
                       </div>
	            }
               <br />
           </div>
       </div>
    
       <div class="editor-field">
            <div>@Html.EditorFor(e=>e.SurveyTitleTextBox.text)
               
             </div>
           <div>@Html.ValidationMessageFor(m => m.SurveyTitleTextBox.text)</div>
       </div>
        
    <div class="editor-label">
        <br />
        <div>@Html.LabelFor(e => e.SelectedQuestion)
            
            @if (TempData["questionMessage"] != null)
            {
                <div style="color: red">
                    @TempData["questionMessage"]
                </div>
            }
            <br />
        </div>
    </div>
    
    <div class="editor-field">

        <div>@Html.DropDownListFor(e => e.SelectedQuestion, Model.QuestionsToChoose)</div>
        @Html.ValidationMessageFor(m => m.SelectedQuestion)

    </div>
    
     <div class="editor-label">
          <br />
        <div>@Html.LabelFor(e => e.SelectedType)
           
            @if (TempData["selectedType"] != null)
            {
                <div style="color: red">
                    @TempData["selectedType"]
                </div>
            }
            <br />
        </div>
    </div>
    
    <div class="editor-field">

        <div>@Html.DropDownListFor(e => e.SelectedType, Model.AnswerType)</div>
        @Html.ValidationMessageFor(m => m.SelectedType)

    </div>
    
     <div class="editor-label">
         <br />
        <div>@Html.LabelFor(e => e.Amount_of_answers)
            
            @if (TempData["amountMessage"] != null)
            {
                <div style="color: red">
                    @TempData["amountMessage"]
                </div>
            }
            <br />
        </div>
    </div>
    
    <div class="editor-field">
        <div>@Html.EditorFor(e => e.Amount_of_answers)
           
        </div>
        @Html.ValidationMessageFor(m => m.Amount_of_answers)

    </div>
    
      <div class="editor-label">
           <br />
        <div>@Html.LabelFor(e => e.SelectedAnswer)
           
            @if (TempData["answerMessage"] != null)
            {
                <div style="color: red">
                    @TempData["answerMessage"]
                </div>
            }
            <br />
        </div>
    </div>
    
    <div class="editor-field">

        <div>@Html.DropDownListFor(e => e.SelectedAnswer, Model.AnswersToChoose)</div>
        @Html.ValidationMessageFor(m => m.SelectedAnswer)

    </div>
 
    <br />
       
    <div>
        @if (TempData["message"]!=null)
	    {
		    @TempData["message"]
	    }
    </div>
    
    <input type="submit" value="Zapisz" name="buttonType" />
    <input type="submit" value="Dodaj pytanie"  name="buttonType"/>
}

SurveysSystem/Views/Elements/DeleteSurvey.cshtml
@model SurveysSystem.Models.DeletingSurveyModel

@{
    ViewBag.Title = "DeleteSurvey";
}

<h2>Usuwanie ankiety</h2>

@using (Html.BeginForm("DeleteSurvey", "Elements"))
{
    @Html.ValidationSummary(false)

    <div class="editor-label">
         <br />
        <div>@Html.LabelFor(e => e.SelectedTitle)
           
            @if (TempData["surveyMessage"] != null)
            {
                <div style="color: red">
                    @TempData["surveyMessage"]
                </div>
            }
            <br />
        </div>
    </div>
    
    <div class="editor-field">

        <div>@Html.DropDownListFor(e => e.SelectedTitle, Model.SurveyTitleToChoose, "- Wybierz ankietę -")</div>
        @Html.ValidationMessageFor(m => m.SelectedTitle)

    </div>
    
    <div class="editor-label">
        <br />
        <div>@Html.LabelFor(e => e.SelectedContent)
            
            @if (TempData["contentMessage"] != null)
            {
                <div style="color: red">
                    @TempData["contentMessage"]
                </div>
            }
            <br />
        </div>
    </div>
    
    <div class="editor-field">

        <div>@Html.DropDownListFor(e => e.SelectedContent, Model.ContentToChoose, "- Wybierz treść -")</div>
        @Html.ValidationMessageFor(m => m.SelectedContent)

    </div>
    
    <br />
       
    <div>
        @if (TempData["message"]!=null)
	    {
		    @TempData["message"]
	    }
    </div>
    
    <input type="submit" value="Usuń" />
}

SurveysSystem/Views/Elements/Edit.cshtml
@*odwołanie się do modelu widoku*@
@model ElementsModel

@using SurveysSystem.Models

@*tytuł widoku*@
@{
    ViewBag.Title = "Edycja";
}

@*tytuł widoku, który będzie wyświetlony na stronie*@
<h2>Edycja</h2>

@*zaznaczenie, że widok należy do akcji Edit w kontrolerze ElementsController*@
@using (Html.BeginForm("Edit", "Elements", FormMethod.Post, new { id = "Edit" }))
{
    //zaznaczenie, że wymaga się wyświetlania informacji o błędach
        
    @Html.ValidationSummary(false)
  
    <div>
        @*pole edycji dla obiektu Question*@
         <div class="editor-label">
             <br />
            @*Label jako informacja*@
           <div>@Html.LabelFor(e => e.Question) 
                  
               @*wyświetlanie informacji o błedach, jeżeli jest  *@
               @if (TempData["questionMessage"] != null)
               {
                   <div style="color:red">
		                @TempData["questionMessage"]
                   </div>
               }
               <br />
           </div>
      </div>
@*  EditorFor - jako pole do uzupełnienia*@
       <div class="editor-field">
            <div>@Html.EditorFor(e => e.Question.text)</div>
   @*        wiadomość walidacji dla obiektu*@
           <div>@Html.ValidationMessageFor(m => m.Question.text)</div>
       </div>
   
         @*pole edycji dla obiektu Amount_of_answers *@

      <div class="editor-label">
             <br />
          @*Label jako informacja*@
           <div>@Html.LabelFor(e => e.Amount_of_answers)
               
                @*wyświetlanie informacji o błedach, jeżeli jest  *@
               @if (TempData["amountMessage"] != null)
               {
                   <div style="color:red">
		                @TempData["amountMessage"] 
                    </div>
               }
               <br />
           </div>
      </div>

    @*lista wyboru - DropDownList dla ilosci odpowiedzi*@
       <div class="editor-field">
           <div>@Html.DropDownListFor(e => e.Amount_of_answers, (SelectList)ViewBag.Numbers, new { onchange = "this.form.submit();" }) 
           </div>
           @*        wiadomość walidacji dla obiektu*@
           <div>@Html.ValidationMessageFor(m => m.Amount_of_answers)</div>
       </div>
    </div>  
    
    //wyswietlanie tylu pól edycji dla odpowiedzi, jaką wybrano wcześniej ich liczbę
      for (int i = 0; i < Model.Amount_of_answers; i++)
      {
        <div class="answerLabel">
            <br />
               <div>@Html.LabelFor(e => e.Answer)
               
                   @if (TempData["answerMessage"] != null)
                   {
                       <div style="color:red">
		                    @TempData["answerMessage"] 
                        </div>
                   }
                   <br />
               </div>
          </div>
    
           <div class="answerFields">
                <div>@Html.EditorFor(e => e.Answer[i].text)
               
                 </div>
               <div>@Html.ValidationMessageFor(m => m.Answer[i].text)</div>
           </div>
           }

           <br />
           
    //wyswietlanie końcowej wiadomości o wyniku dodania nowych elementów do bazy
    <div>
        @if (TempData["message"] != null)
        {
		    @TempData["message"]
        }
    </div>
    
    //przycisk wywołujący akcjęzapisu danych do bazy
    <input type="submit" value="Zapisz"  name="buttonType"/>
    <input type="submit" value="Nowe pytanie"  name="buttonType"/>
}